title: å­¦ä¹ ç¬”è®°
description: ğŸˆéšä¾¿å†™å†™
baseurl: "/ziyuan"
url: "https://blog.52013120.xyz"
theme: minima
locale: "zh-CN"
minima:
  skin: dark
header_pages:
  - å…³äº.md
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "tables", "highlight"]
