title: å­¦ä¹ ç¬”è®°
description: ğŸˆéšä¾¿å†™å†™
baseurl: "/ziyuan"
url: "https://blog.52013120.xyz"
theme: minima
locale: "zh-CN"
social_links:
  - { platform: github,         user_url: "https://github.com/sky22333/ziyuan" }
header_pages:
  - å…³äº.md
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "tables", "highlight"]
